/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* location of default background file */
#define ASHXP_BG_FILE_LOCATION "/home/josh/puff/etc/images/"

/* location of default font */
#define ASHXP_FONTFILE "/home/josh/puff/etc/fonts/FreeMonoBold.ttf"

/* swap localtime for gmtime */
/* #undef BUG_GMTIME */

/* Autoconf-generated architecture */
#define BUILD_OS i686-pc-linux-gnu

/* Enable shared libraries */
#define ENABLE_SHARED 0

/* Define to 1 if you have the <algorithm> header file. */
#define HAVE_ALGORITHM 1

/* Define to 1 if you have the `atoi' function. */
#define HAVE_ATOI 1

/* Define to 1 if you have the `basename' function. */
#define HAVE_BASENAME 1

/* Define to 1 if you have the `cbrt' function. */
#define HAVE_CBRT 1

/* Define to 1 if you have the `ceil' function. */
#define HAVE_CEIL 1

/* Define to 1 if you have the `ceilf' function. */
#define HAVE_CEILF 1

/* Define to 1 if you have the <cmapf.h> header file. */
/* #undef HAVE_CMAPF_H */

/* Define to 1 if you have the <cmath> header file. */
#define HAVE_CMATH 1

/* Define to 1 if you have the <cstdlib> header file. */
#define HAVE_CSTDLIB 1

/* Define to 1 if you have the <ctime> header file. */
#define HAVE_CTIME 1

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `exp10' function. */
#define HAVE_EXP10 1

/* Define to 1 if you have the `floor' function. */
#define HAVE_FLOOR 1

/* Define to 1 if you have the `floorf' function. */
#define HAVE_FLOORF 1

/* Define to 1 if you have the <fstream> header file. */
#define HAVE_FSTREAM 1

/* Define to 1 if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the `getopt_long' function. */
#define HAVE_GETOPT_LONG 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <iomanip> header file. */
#define HAVE_IOMANIP 1

/* Define to 1 if you have the <iostream> header file. */
#define HAVE_IOSTREAM 1

/* Define to 1 if you have the <jpeglib.h> header file. */
#define HAVE_JPEGLIB_H 1

/* Define to 1 if you have the `crypt' library (-lcrypt). */
#define HAVE_LIBCRYPT 1

/* Define to 1 if you have the `dmapf' library (-ldmapf). */
/* #undef HAVE_LIBDMAPF */

/* Define to 1 if you have the `freetype' library (-lfreetype). */
#define HAVE_LIBFREETYPE 1

/* Define to 1 if you have the <libgen.h> header file. */
#define HAVE_LIBGEN_H 1

/* Define to 1 if you have the `jpeg' library (-ljpeg). */
#define HAVE_LIBJPEG 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the `netcdf' library (-lnetcdf). */
#define HAVE_LIBNETCDF 1

/* define to 1 if you have libnetcdf_c++ */
#define HAVE_LIBNETCDF_CXX 1

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the `udport' library (-ludport). */
/* #undef HAVE_LIBUDPORT */

/* Define to 1 if you have the `udunits' library (-ludunits). */
#define HAVE_LIBUDUNITS 1

/* Define to 1 if you have the <list> header file. */
#define HAVE_LIST 1

/* Define to 1 if you have the `logf' function. */
#define HAVE_LOGF 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mkstemp' function. */
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the <netcdfcpp.h> header file. */
#define HAVE_NETCDFCPP_H 1

/* Define to 1 if you have the <netcdf.h> header file. */
#define HAVE_NETCDF_H 1

/* Define to 1 if you have the `printf' function. */
#define HAVE_PRINTF 1

/* Define to 1 if you have the `putenv' function. */
#define HAVE_PUTENV 1

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the `sscanf' function. */
#define HAVE_SSCANF 1

/* Define to 1 if you have the <sstream> header file. */
#define HAVE_SSTREAM 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <string> header file. */
#define HAVE_STRING 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <strstream> header file. */
#define HAVE_STRSTREAM 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `tmpnam' function. */
#define HAVE_TMPNAM 1

/* Define to 1 if you have the `toupper' function. */
#define HAVE_TOUPPER 1

/* Define to 1 if you have the <udunits.h> header file. */
#define HAVE_UDUNITS_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <vector> header file. */
#define HAVE_VECTOR 1

/* Name of package */
#define PACKAGE "puff-uaf"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "rorik@gi.alaska.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "puff"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "puff 2.2.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "puff-uaf"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.2.1"

/* make additional statistical information */
/* #undef PUFF_STATISTICS */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* location of udunits data file */
/* #undef UDUNITS_DAT */

/* Version number of package */
#define VERSION "2.2.1"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */
